name: armv8打包

on:
  repository_dispatch:
    types: [db]
  workflow_dispatch:
    inputs:
      ssh:
        description: 'db'
        required: false
        default: 'false'
  schedule:
    - cron: 30 23 * * *

env:
  UPLOAD_BIN_DIR: true
  UPLOAD_RELEASE: true
  TZ: Asia/Shanghai

jobs:

  kbuild0: #开发+0版
    runs-on: ubuntu-18.04
    steps:    
    - name: Checkout
      uses: actions/checkout@main
    - name: Initialization environment #初始化环境
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo rm -rf /etc/apt/sources.list.d/* /usr/share/dotnet /usr/local/lib/android /opt/ghc
        sudo -E apt-get -qq update
        sudo -E apt-get -qq install $(curl -fsSL git.io/depends-ubuntu-1804)
        sudo -E apt-get -qq autoremove --purge
        sudo -E apt-get -qq clean
        sudo timedatectl set-timezone "$TZ"
        sudo mkdir -p /workdir
        sudo chown $USER:$GROUPS /workdir
    - name: Build firmware #打包
      id: build
      run: |
        cd /opt
        sudo wget https://github.com/bin20088/Bin/releases/download/公告/img+0.tar
        sudo tar xvf *.tar
        sudo xz -d *.img.xz
        sudo tar zxvf *.tar.gz
        sudo mkdir imgs
        sudo mv *.img imgs
        cd /opt/openwrt
        sudo wget https://github.com/bin20088/Bin/releases/download/armv8开发版/openwrt-armvirt-64-default-rootfs.tar.gz
        sudo ./mk_s905x3_opimg.sh
        sudo ./mk_n1_opimg.sh
        sudo ./mk_beikeyun_opimg.sh
        sudo ./mk_l1pro_opimg.sh
        sudo ./n1-to-vplus.sh
        echo "::set-output name=status::success"
    - name: Organize files #此处操作是发布时因权限问题失败
      id: organize
      if: steps.build.outputs.status == 'success' && !cancelled()
      run: |
        sudo cp /opt/openwrt/tmp/*.img /workdir
        cd /workdir
        bzip2 *.img
        echo "FIRMWARE=$PWD" >> $GITHUB_ENV
        echo "::set-output name=status::success"
    - name: Upload bin directory #上传artifact
      uses: actions/upload-artifact@main
      if: steps.organize.outputs.status == 'success' && env.UPLOAD_BIN_DIR == 'true' && !cancelled()
      with:
        name: k+0
        path: ${{ env.FIRMWARE }}
    - name: Create release #发布
      uses: ncipollo/release-action@v1
      if: env.UPLOAD_RELEASE == 'true' && steps.organize.outputs.status == 'success' && !cancelled()
      with:
        allowUpdates: true
        tag: armv8开发版
        commit: master
        token: ${{ secrets.RELEASES_TOKEN }}
        artifacts: ${{ env.FIRMWARE }}


  kbuild: #开发+版
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout
      uses: actions/checkout@main
    - name: Initialization environment #初始化环境
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo rm -rf /etc/apt/sources.list.d/* /usr/share/dotnet /usr/local/lib/android /opt/ghc
        sudo -E apt-get -qq update
        sudo -E apt-get -qq install $(curl -fsSL git.io/depends-ubuntu-1804)
        sudo -E apt-get -qq autoremove --purge
        sudo -E apt-get -qq clean
        sudo timedatectl set-timezone "$TZ"
        sudo mkdir -p /workdir
        sudo chown $USER:$GROUPS /workdir
    - name: Build firmware #打包
      id: build
      run: |
        cd /opt
        sudo wget https://github.com/bin20088/Bin/releases/download/公告/img+.tar
        sudo tar xvf *.tar
        sudo xz -d *.img.xz
        sudo tar zxvf *.tar.gz
        sudo mkdir imgs
        sudo mv *.img imgs
        cd /opt/openwrt
        sudo wget https://github.com/bin20088/Bin/releases/download/armv8开发版/openwrt-armvirt-64-default-rootfs.tar.gz
        sudo ./mk_s905x3_opimg.sh
        sudo ./mk_n1_opimg.sh
        sudo ./n1-to-vplus.sh
        echo "::set-output name=status::success"
    - name: Organize files #此处操作是发布时因权限问题失败
      id: organize
      if: steps.build.outputs.status == 'success' && !cancelled()
      run: |
        sudo cp /opt/openwrt/tmp/*.img /workdir
        cd /workdir
        bzip2 *.img
        echo "FIRMWARE=$PWD" >> $GITHUB_ENV
        echo "::set-output name=status::success"
    - name: Upload bin directory #上传artifact
      uses: actions/upload-artifact@main
      if: steps.organize.outputs.status == 'success' && env.UPLOAD_BIN_DIR == 'true' && !cancelled()
      with:
        name: k+
        path: ${{ env.FIRMWARE }}
    - name: Create release #发布
      uses: ncipollo/release-action@v1
      if: env.UPLOAD_RELEASE == 'true' && steps.organize.outputs.status == 'success' && !cancelled()
      with:
        allowUpdates: true
        tag: armv8开发版
        commit: master
        token: ${{ secrets.RELEASES_TOKEN }}
        artifacts: ${{ env.FIRMWARE }}


  wbuild0: #稳定+0版
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout
      uses: actions/checkout@main
    - name: Initialization environment #初始化环境
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo rm -rf /etc/apt/sources.list.d/* /usr/share/dotnet /usr/local/lib/android /opt/ghc
        sudo -E apt-get -qq update
        sudo -E apt-get -qq install $(curl -fsSL git.io/depends-ubuntu-1804)
        sudo -E apt-get -qq autoremove --purge
        sudo -E apt-get -qq clean
        sudo timedatectl set-timezone "$TZ"
        sudo mkdir -p /workdir
        sudo chown $USER:$GROUPS /workdir
    - name: Build firmware #打包
      id: build
      run: |
        cd /opt
        sudo wget https://github.com/bin20088/Bin/releases/download/公告/img+0.tar
        sudo tar xvf *.tar
        sudo xz -d *.img.xz
        sudo tar zxvf *.tar.gz
        sudo mkdir imgs
        sudo mv *.img imgs
        cd /opt/openwrt
        sudo wget https://github.com/bin20088/Bin/releases/download/armv8稳定版/openwrt-armvirt-64-default-rootfs.tar.gz
        sudo ./mk_s905x3_opimg.sh
        sudo ./mk_n1_opimg.sh
        sudo ./mk_beikeyun_opimg.sh
        sudo ./mk_l1pro_opimg.sh
        sudo ./n1-to-vplus.sh
        echo "::set-output name=status::success"
    - name: Organize files #此处操作是发布时因权限问题失败
      id: organize
      if: steps.build.outputs.status == 'success' && !cancelled()
      run: |
        sudo cp /opt/openwrt/tmp/*.img /workdir
        cd /workdir
        bzip2 *.img
        echo "FIRMWARE=$PWD" >> $GITHUB_ENV
        echo "::set-output name=status::success"
    - name: Upload bin directory #上传artifact
      uses: actions/upload-artifact@main
      if: steps.organize.outputs.status == 'success' && env.UPLOAD_BIN_DIR == 'true' && !cancelled()
      with:
        name: w+0
        path: ${{ env.FIRMWARE }}
    - name: Create release #发布
      uses: ncipollo/release-action@v1
      if: env.UPLOAD_RELEASE == 'true' && steps.organize.outputs.status == 'success' && !cancelled()
      with:
        allowUpdates: true
        tag: armv8稳定版
        commit: master
        token: ${{ secrets.RELEASES_TOKEN }}
        artifacts: ${{ env.FIRMWARE }}


  wbuild: #稳定+版
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout
      uses: actions/checkout@main
    - name: Initialization environment #初始化环境
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo rm -rf /etc/apt/sources.list.d/* /usr/share/dotnet /usr/local/lib/android /opt/ghc
        sudo -E apt-get -qq update
        sudo -E apt-get -qq install $(curl -fsSL git.io/depends-ubuntu-1804)
        sudo -E apt-get -qq autoremove --purge
        sudo -E apt-get -qq clean
        sudo timedatectl set-timezone "$TZ"
        sudo mkdir -p /workdir
        sudo chown $USER:$GROUPS /workdir
    - name: Build firmware #打包
      id: build
      run: |
        cd /opt
        sudo wget https://github.com/bin20088/Bin/releases/download/公告/img+.tar
        sudo tar xvf *.tar
        sudo xz -d *.img.xz
        sudo tar zxvf *.tar.gz
        sudo mkdir imgs
        sudo mv *.img imgs
        cd /opt/openwrt
        sudo wget https://github.com/bin20088/Bin/releases/download/armv8稳定版/openwrt-armvirt-64-default-rootfs.tar.gz
        sudo ./mk_s905x3_opimg.sh
        sudo ./mk_n1_opimg.sh
        sudo ./n1-to-vplus.sh
        echo "::set-output name=status::success"
    - name: Organize files #此处操作是发布时因权限问题失败
      id: organize
      if: steps.build.outputs.status == 'success' && !cancelled()
      run: |
        sudo cp /opt/openwrt/tmp/*.img /workdir
        cd /workdir
        bzip2 *.img
        echo "FIRMWARE=$PWD" >> $GITHUB_ENV
        echo "::set-output name=status::success"
    - name: Upload bin directory #上传artifact
      uses: actions/upload-artifact@main
      if: steps.organize.outputs.status == 'success' && env.UPLOAD_BIN_DIR == 'true' && !cancelled()
      with:
        name: w+
        path: ${{ env.FIRMWARE }}
    - name: Create release #发布
      uses: ncipollo/release-action@v1
      if: env.UPLOAD_RELEASE == 'true' && steps.organize.outputs.status == 'success' && !cancelled()
      with:
        allowUpdates: true
        tag: armv8稳定版
        commit: master
        token: ${{ secrets.RELEASES_TOKEN }}
        artifacts: ${{ env.FIRMWARE }}


  over:
    needs: [kbuild0, kbuild, wbuild0, wbuild]
    runs-on: ubuntu-18.04
    steps:
    - name: WeChat notification
      run: curl https://sc.ftqq.com/${{ secrets.ServerChan }}.send?text=打包成功完成
