name: 公告

on:
  repository_dispatch:
    types: 公告
#  watch:
#    types: started
#  schedule:
#    - cron: 0 0 * * *
      
env:
  FILE_NAME: 公告      

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
    
    - name: set-env
      run: echo "::set-env name=DATE::$(TZ=UTC-8 date "+%Y.%m.%d %H:%M:%S")"

    - name: Create release
      uses: ncipollo/release-action@v1
      with:
        name: ${{ env.DATE }} 🚀 公告 | 有重大更新时发布
        allowUpdates: true
        tag: 公告
        commit: master
        token: ${{ secrets.RELEASES_TOKEN }}
        body: |
            🚀 推荐本人[➦自用稳定机场](https://moo.pet/Rxd4O),🚀折扣码到期，期待下次再有。      
            🚀目前已基本稳定，开始继续正常发布。 [➦我的网盘](http://256pd.top:9666)继续保留R20.6.18版本供机油备用，也同时每天更新最新固件，如需单独下载依赖及ipk，也可以在 [➦我的网盘](http://256pd.top:9666)里找到   
            🚀固件说明及公告请到[➦10月3日公告页](https://github.com/bin20088/Bin/blob/master/.github/workflows/公告.md)查看。 各位务必看看10月3日的公告，以免出错。   【顺利测试成功，客官们尽情享用吧】
          
    - name: WeChat notification
      run: curl https://sc.ftqq.com/${{ secrets.ServerChan }}.send?text=${{ env.FILE_NAME }}发布成功
